import PDFDocument from 'pdfkit';
import pool from './db.js';
import { prettyValue } from './summary.js';

// Build a doctor-ready PDF: patient intake summary + AI summary + prescription.
export async function visitPDF(visitId) {
  const { rows: visit } = await pool.query(
    `SELECT v.*, p.name, p.age, p.gender, p.phone
       FROM visits v JOIN patients p ON p.id = v.patient_id WHERE v.id = $1`, [visitId]);
  const { rows: summ } = await pool.query('SELECT * FROM summaries WHERE visit_id = $1', [visitId]);
  const { rows: answers } = await pool.query(
    `SELECT a.question_id, a.value, q.text_en, q.section
       FROM answers a JOIN questions q ON q.id = a.question_id
      WHERE a.visit_id = $1 ORDER BY a.id`, [visitId]);

  const v = visit[0] || {};
  const s = summ?.[0]?.structured || {};
  const ai = summ?.[0]?.ai_summary || '';
  const flags = v.red_flags || [];

  const doc = new PDFDocument({ size: 'A4', margins: { top: 48, bottom: 48, left: 48, right: 48 } });

  // ---------- header ----------
  doc.fontSize(20).fillColor('#0e7490').text('MediKiosk — Visit Summary', { continued: false });
  doc.moveDown(0.2);
  doc.fontSize(9).fillColor('#666')
     .text(`Visit #${v.id}${v.token ? `  ·  Token: ${v.token}` : ''}  ·  Generated ${new Date().toLocaleString('en-IN')}`)
     .text(`${v.name || '—'}  ·  ${v.age || '—'} yrs  ·  ${v.gender || '—'}  ·  ${v.phone || '—'}`);
  doc.moveDown(0.6);

  // ---------- red flags ----------
  if (flags.length) {
    doc.fontSize(11).fillColor('#b91c1c').text('⚠️ URGENT FLAGS (rule-based, not a diagnosis)', { continued: false });
    for (const f of flags) doc.fontSize(10).fillColor('#b91c1c').text(`  • ${f}`);
    doc.moveDown(0.6);
  }

  // ---------- structured summary ----------
  doc.fontSize(13).fillColor('#0e7490').text('Patient Intake Summary', { continued: false });
  doc.moveDown(0.3);
  const rows = [
    ['Chief complaint', s.chief_complaint],
    ['Duration', s.duration],
    ['Severity', s.severity],
    ...(s.pain ? [
      ['Pain started', s.pain.started],
      ['Pain severity', s.pain.severity],
      ['Pain character', s.pain.character],
      ['Spreads to', s.pain.radiation],
      ['Breathlessness', s.pain.breathlessness],
      ['Dizziness', s.pain.dizziness],
      ['Worse with', s.pain.worse_with],
    ] : []),
    ['Existing conditions', s.existing_conditions],
    ['Past surgery', s.surgery],
    ['Current medicines', s.medications],
    ['Allergies', s.allergies],
    ['Family history', s.family_history],
    ['Lifestyle', s.lifestyle],
    ['Sleep', s.sleep],
    ['Ayurveda', s.ayurveda],
  ];
  for (const [k, val] of rows) {
    doc.fontSize(10).fillColor('#333').text(k + ':', { continued: true });
    doc.fillColor('#000').text('  ' + (val || 'Not reported'));
  }
  doc.moveDown(0.4);

  // ---------- patient's own words ----------
  if (v.patient_note) {
    doc.fontSize(13).fillColor('#0e7490').text("Patient's Own Words", { continued: false });
    doc.moveDown(0.2);
    doc.fontSize(10).fillColor('#333').text('"' + v.patient_note + '"');
    doc.moveDown(0.4);
  }

  // ---------- AI summary ----------
  if (ai) {
    doc.fontSize(13).fillColor('#0e7490').text('AI Clinical Summary (AI-drafted — doctor must review)', { continued: false });
    doc.moveDown(0.2);
    doc.fontSize(9.5).fillColor('#333').text(ai, { lineGap: 2 });
    doc.moveDown(0.4);
  }

  // ---------- consultation ----------
  doc.fontSize(13).fillColor('#0e7490').text('Consultation', { continued: false });
  doc.moveDown(0.3);
  doc.fontSize(10).fillColor('#333').text('Prescription / treatment:');
  doc.fontSize(10).fillColor('#000').text(summ?.[0]?.prescription || '—');
  doc.moveDown(0.3);
  doc.fontSize(10).fillColor('#333').text("Doctor's notes:");
  doc.fontSize(10).fillColor('#000').text(summ?.[0]?.doctor_notes || '—');
  doc.moveDown(0.8);
  doc.fontSize(10).fillColor('#333').text('Doctor signature: ____________________________________');
  doc.moveDown(0.4);
  doc.fontSize(8).fillColor('#999').text('Generated by MediKiosk — the AI summary is an organizational aid and must be reviewed by a qualified doctor. Not a diagnosis.');

  // ---------- raw answers (appendix) ----------
  doc.addPage();
  doc.fontSize(13).fillColor('#0e7490').text('Appendix — Raw Answers', { continued: false });
  doc.moveDown(0.3);
  for (const a of answers) {
    doc.fontSize(9.5).fillColor('#555').text(`${a.text_en}:`, { continued: true });
    doc.fillColor('#000').text(`  ${prettyValue(a.question_id, a.value)}`);
  }

  return doc;
}